#ifndef TEST_SUITE_CONFIG_HEADER
#define TEST_SUITE_CONFIG_HEADER

#define SCREEN_WIDTH  160
#define SCREEN_HEIGHT 160

#define MAX_SUBPROGRAMS  20
#define TESTS_AVAILABLE  40
#define TEST_NAME_LENGTH 32

#define FONT_WIDTH   6
#define FONT_HEIGHT  8
#define FONT_SPACING 0
#define SELECTED_FONT FONT_6X8

#endif
